---
title: "Assignment week1"
output: html_notebook
---

Read data and load necessary libraries
```{r}
library(dplyr)
library(tidyr)
data <- read.delim("household_power_consumption.txt", sep = ";")
```

select dates of interest + combine Date & Time
```{r}
df <- filter(data, Date == "1/2/2007" | Date == "2/2/2007")
df <- unite(df, col = "Datetime", Date:Time, sep = " ")
```

Plot1
```{r}
hist(as.numeric(df$Global_active_power), col = "red", main = "Global active power", xlab = "Global Active Power (kilowatts)")
```
plot2
```{r}
with(df, plot(as.numeric(df$Global_active_power)~ date, type = "l",ylab = "Global Active Power (kilowatts" ))
```
plot3
```{r}
with(df, plot(Sub_metering_1~ date, type = "l", ylab = "Energy sub metering"))
lines(df$Sub_metering_2~ date, col = "red")
lines(df$Sub_metering_3~ date, col = "blue")
legend(, x = "topright", legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty = c(1,1,1),col = c("black","red","blue"))
```
plot4
```{r}
par(mfrow=c(2,2)) ##split screen in 4 for plots
x <- c("Thu", "Fri", "Sat")
##plot1
with(df, plot(as.numeric(df$Global_active_power)~ date, type = "l",ylab = "Global Active Power", ))
##plot2
with(df, plot(as.numeric(df$Voltage)~ date, type = "l",ylab = "Voltage"))
##plot3
with(df, plot(Sub_metering_1~ date, type = "l", ylab = "Energy sub metering"))
lines(df$Sub_metering_2~ date, col = "red")
lines(df$Sub_metering_3~ date, col = "blue")
legend(, x = "topright", legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty = c(1,1,1),col = c("black","red","blue"))
##plot4
with(df, plot(Global_reactive_power~ date, type = "l"))
```

